// swift-tools-version: 5.9
// Generated by tool/pm3_apple/configure_swiftpm.py after the immutable Release exists.
import PackageDescription

let package = Package(
    name: "tagentra_pm3",
    platforms: [.iOS(.v15)],
    products: [.library(name: "tagentra-pm3", targets: ["tagentra_pm3"])],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework")
    ],
    targets: [
        .binaryTarget(
            name: "TagentraPM3Core",
            url: "https://github.com/fly6516/tagentra/releases/download/pm3core-v4.21611-t2/TagentraPM3Core.xcframework.zip",
            checksum: "013635d12f5b08b617ad115c64858b9c77ed2a36523e5584c749994255498ed3"
        ),
        .target(
            name: "tagentra_pm3",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                "TagentraPM3Core"
            ]
        )
    ]
)
